package com.il76.playlistmaker.ui.theme

import androidx.compose.ui.graphics.Color

object LightThemeColors {
    val black = Color(0xFF000000)
    val white = Color(0xFFFFFFFF)
    val playerInfoName = Color(0xFF1A1B22)
    val settingsText = Color(0xFF000000)
    val backgroundMain = Color(0xFF3772E7)
    val backgroundSecondary = Color(0xFFFFFFFF)
    val switcherThumb = Color(0xFFCECFD2)
    val switcherTrack = Color(0xFFF0F1F3)
    val clearIconFill = Color(0xFFAEAFB4)
    val mainHeader = Color(0xFFFFFFFF)
    val mainIconFill = Color(0xFF1A1B22)
    val settingsIconFill = Color(0xFFAEAFB4)
    val backIconFill = Color(0xFF1A1B22)
    val searchEditMain = Color(0xFFAEAFB4)
    val searchEditBg = Color(0xFFE6E8EB)
    val playerIconBg = Color(0xFFC5C6C7)
    val playerIconPlay = Color(0xFF000000)
    val playerIconPlayInner = Color(0xFFFFFFFF)
    val progressbarTint = Color(0xFF3772E7)
    val bottomNavigationBorder = Color(0xFFE6E8EB)
    val bottomNavigationItemActive = Color(0xFF3772E7)
    val bottomNavigationItemDefault = Color(0xFF1A1B22)
    val bottomSheetHandle = Color(0xFFE6E8EB)
    val playlistCreateIconFill = Color(0xFFAEAFB4)
    val playlistCreateDisabled = Color(0xFFAEAFB4)
    val playlistCreateEnabled = Color(0xFF3772E7)
    val playlistCreateEmptyField = Color(0xFFDADADA)
    val playlistCreateFilledField = Color(0xFF3772E7)
    val dialogColor = Color(0xFF000000)
    val playlistIconFill = Color(0xFF1A1B22)
}

object DarkThemeColors {
    val black = Color(0xFF000000)
    val white = Color(0xFFFFFFFF)
    val playerInfoName = Color(0xFFAEAFB4)
    val settingsText = Color(0xFFFFFFFF)
    val backgroundMain = Color(0xFF1A1B22)
    val backgroundSecondary = Color(0xFF1A1B22)
    val switcherThumb = Color(0xFF3772E7)
    val switcherTrack = Color(0xFF5A6887)
    val clearIconFill = Color(0xFF1A1B22)
    val mainHeader = Color(0xFFFFFFFF)
    val mainIconFill = Color(0xFF1A1B22)
    val settingsIconFill = Color(0xFFFFFFFF)
    val backIconFill = Color(0xFFFFFFFF)
    val searchEditMain = Color(0xFF1A1B22)
    val searchEditBg = Color(0xFFFFFFFF)
    val playerIconBg = Color(0xFF535459)
    val playerIconPlay = Color(0xFFFFFFFF)
    val playerIconPlayInner = Color(0xFF000000)
    val progressbarTint = Color(0xFF3772E7)
    val bottomNavigationBorder = Color(0xFFE6E8EB)
    val bottomNavigationItemActive = Color(0xFF3772E7)
    val bottomNavigationItemDefault = Color(0xFFFFFFFF)
    val bottomSheetHandle = Color(0xFFFFFFFF)
    val playlistCreateIconFill = Color(0xFFAEAFB4)
    val playlistCreateDisabled = Color(0xFFAEAFB4)
    val playlistCreateEnabled = Color(0xFF3772E7)
    val playlistCreateEmptyField = Color(0xFFFFFFFF)
    val playlistCreateFilledField = Color(0xFF3772E7)
    val dialogColor = Color(0xFFFFFFFF)
    val playlistIconFill = Color(0xFF1A1B22)
}